# Generated by Django 4.2.1 on 2025-01-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("-created_at",)},
        ),
    ]
